declare module "mobx";
declare module "mobx-react";
declare module "react-grid-layout";
declare module "@ant-design/charts";
declare module "react-amap";
declare module "react-magic";
declare module "aphrodite"
declare module "react-magic/lib"
declare module "h5-api"